package com.maliktraders.viewer;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;
public class MainActivity extends Activity{
 final int NAVY=Color.rgb(10,18,33),PANEL=Color.rgb(19,30,49),LINE=Color.rgb(43,58,79),TEAL=Color.rgb(35,203,180),GOLD=Color.rgb(219,184,109),TEXT=Color.rgb(233,240,248),MUTED=Color.rgb(151,169,190);
 LinearLayout body;String tab="Dashboard",source="",cache="";int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}
 TextView t(String s,int z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);if(b)v.setTypeface(null,1);v.setPadding(0,dp(5),0,dp(5));return v;}
 GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));g.setStroke(dp(1),LINE);return g;}
 public void onCreate(Bundle b){super.onCreate(b);source=getPreferences(0).getString("source","");cache=getPreferences(0).getString("cache","");render();if(!source.isEmpty())sync(false);}
 LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(14),dp(16),dp(14));c.setBackground(bg(PANEL,16));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(12));body.addView(c,p);return c;}
 void render(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);TextView h=t("MT   MALIK TRADERS",20,GOLD,true);h.setPadding(dp(18),dp(20),dp(18),dp(18));h.setBackgroundColor(PANEL);root.addView(h);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(16),dp(16),dp(16),dp(20));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));page();LinearLayout nav=new LinearLayout(this);for(String n:new String[]{"Dashboard","Accounts","Search","Settings"}){TextView x=t(n,11,n.equals(tab)?TEAL:MUTED,n.equals(tab));x.setGravity(17);x.setOnClickListener(v->{tab=n;render();});nav.addView(x,new LinearLayout.LayoutParams(0,dp(58),1));}nav.setBackgroundColor(PANEL);root.addView(nav);setContentView(root);}
 JSONObject data(){try{return cache.isEmpty()?null:new JSONObject(cache);}catch(Exception e){return null;}}
 void page(){if(tab.equals("Settings"))settings();else if(tab.equals("Accounts"))accounts("");else if(tab.equals("Search"))search();else dash();}
 void dash(){JSONObject j=data();LinearLayout c=card();c.addView(t(j==null?"DATA NOT LOADED":"● LIVE LEDGER DATA",14,j==null?GOLD:TEAL,true));if(j!=null){c.addView(t(j.optInt("accountCount",0)+" Accounts",24,TEXT,true));c.addView(t("Updated: "+j.optString("generatedAt",""),11,MUTED,false));}TextView r=t("REFRESH FROM ONEDRIVE",13,TEAL,true);r.setGravity(17);r.setPadding(8,14,8,14);r.setBackground(bg(Color.rgb(25,39,60),12));r.setOnClickListener(v->sync(true));c.addView(r);}
 void accounts(String q){JSONObject j=data();if(j==null){card().addView(t("Refresh data first.",14,MUTED,false));return;}JSONArray a=j.optJSONArray("accounts");for(int i=0;a!=null&&i<a.length();i++){JSONObject o=a.optJSONObject(i);String n=o.optString("name");if(!q.isEmpty()&&!n.toLowerCase().contains(q.toLowerCase()))continue;LinearLayout c=card();c.addView(t(n,16,TEXT,true));c.addView(t("Closing: PKR "+o.optDouble("closingBalance",0)+"  "+o.optString("drCr"),13,TEAL,true));c.addView(t(o.optInt("entries",0)+" transactions",11,MUTED,false));}}
 void search(){EditText e=new EditText(this);e.setHint("Search account name");e.setTextColor(TEXT);e.setHintTextColor(MUTED);body.addView(e);TextView b=t("SEARCH",13,TEAL,true);b.setGravity(17);b.setOnClickListener(v->{String q=e.getText().toString();body.removeViews(1,body.getChildCount()-1);accounts(q);});body.addView(b);}
 void settings(){LinearLayout c=card();c.addView(t("OneDrive JSON Share Link",17,TEXT,true));EditText e=new EditText(this);e.setText(source);e.setHint("https://1drv.ms/...");e.setTextColor(TEXT);e.setHintTextColor(MUTED);c.addView(e);TextView s=t("SAVE & SYNC",13,TEAL,true);s.setGravity(17);s.setOnClickListener(v->{source=e.getText().toString().trim();getPreferences(0).edit().putString("source",source).apply();sync(true);});c.addView(s);}
 void sync(boolean tell){if(source.isEmpty()){tab="Settings";render();return;}new Thread(()->{try{String u=source;if(u.contains("1drv.ms")&&!u.contains("download=1"))u+=(u.contains("?")?"&":"?")+"download=1";HttpURLConnection h=(HttpURLConnection)new URL(u).openConnection();h.setInstanceFollowRedirects(true);h.setConnectTimeout(15000);h.setReadTimeout(20000);h.setRequestProperty("User-Agent","Mozilla/5.0");InputStream in=h.getInputStream();ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=in.read(b))>0&&out.size()<10000000)out.write(b,0,n);String d=new String(out.toByteArray(),StandardCharsets.UTF_8).trim();new JSONObject(d);cache=d;getPreferences(0).edit().putString("cache",d).apply();runOnUiThread(()->{render();Toast.makeText(this,"Latest OneDrive data loaded",Toast.LENGTH_SHORT).show();});}catch(Exception e){runOnUiThread(()->Toast.makeText(this,"OneDrive sync failed: "+e.getMessage(),Toast.LENGTH_LONG).show());}}).start();}
}