package com.maliktraders.viewer;

import android.app.*; import android.os.*; import android.content.*; import android.graphics.*; import android.graphics.drawable.GradientDrawable; import android.view.*; import android.widget.*;
import java.io.*; import java.net.*; import java.nio.charset.StandardCharsets;

public class MainActivity extends Activity {
 final int NAVY=Color.rgb(10,18,33),PANEL=Color.rgb(19,30,49),LINE=Color.rgb(43,58,79),TEAL=Color.rgb(35,203,180),GOLD=Color.rgb(219,184,109),TEXT=Color.rgb(233,240,248),MUTED=Color.rgb(151,169,190);
 LinearLayout body; String tab="Dashboard"; String source=""; String last="Never synced";
 int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}
 TextView t(String s,int z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);if(b)v.setTypeface(null,1);return v;}
 GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));g.setStroke(dp(1),LINE);return g;}
 TextView button(String s){TextView b=t(s,13,TEAL,true);b.setGravity(17);b.setPadding(dp(12),dp(13),dp(12),dp(13));b.setBackground(bg(Color.rgb(25,39,60),13));return b;}
 @Override public void onCreate(Bundle b){super.onCreate(b);source=getPreferences(0).getString("source","");last=getPreferences(0).getString("last","Never synced");render();if(!source.isEmpty())sync(false);}
 void render(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(NAVY);
  LinearLayout h=new LinearLayout(this);h.setGravity(16);h.setPadding(dp(18),dp(18),dp(18),dp(14));h.setBackgroundColor(PANEL);TextView logo=t("MT",20,GOLD,true);logo.setGravity(17);logo.setBackground(bg(Color.rgb(35,49,69),13));h.addView(logo,new LinearLayout.LayoutParams(dp(48),dp(48)));LinearLayout br=new LinearLayout(this);br.setOrientation(LinearLayout.VERTICAL);br.setPadding(dp(12),0,0,0);br.addView(t("MALIK TRADERS",17,TEXT,true));br.addView(t("ACCOUNTING CONTROL CENTER",10,MUTED,true));h.addView(br);root.addView(h);
  LinearLayout title=new LinearLayout(this);title.setOrientation(LinearLayout.VERTICAL);title.setPadding(dp(18),dp(16),dp(18),dp(10));title.setBackgroundColor(PANEL);title.addView(t(tab,25,Color.WHITE,true));title.addView(t(tab.equals("Dashboard")?"Live accounting overview":"Malik Traders ledger data",12,MUTED,false));root.addView(title);
  ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(16),dp(16),dp(16),dp(20));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));page();
  LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(PANEL);for(String n:new String[]{"Dashboard","Accounts","Search","Reports","Settings"}){TextView x=t(n,10,n.equals(tab)?TEAL:MUTED,n.equals(tab));x.setGravity(17);x.setOnClickListener(v->{tab=n;render();});nav.addView(x,new LinearLayout.LayoutParams(0,dp(58),1));}root.addView(nav);setContentView(root);}
 LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(16),dp(16),dp(16));c.setBackground(bg(PANEL,18));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(12);body.addView(c,p);return c;}
 void page(){if(tab.equals("Settings"))settings();else if(tab.equals("Dashboard"))dash();else{LinearLayout c=card();c.addView(t(tab,18,Color.WHITE,true));c.addView(t(source.isEmpty()?"Connect your private data URL in Settings.":"Connected to your private live ledger feed.",13,MUTED,false));}}
 void dash(){LinearLayout s=card();s.addView(t(source.isEmpty()?"●  DATA SOURCE NOT CONNECTED":"●  PRIVATE LIVE DATA CONNECTED",13,source.isEmpty()?GOLD:TEAL,true));s.addView(t("Last refresh: "+last,11,MUTED,false));TextView b=button("REFRESH LATEST DATA");b.setOnClickListener(v->sync(true));s.addView(b);
  LinearLayout a=card();a.addView(t("RECEIVABLE",10,MUTED,true));a.addView(t("PKR —",25,TEAL,true));a.addView(t("Figures populate when your sync feed supplies ledger data.",11,MUTED,false));
  LinearLayout p=card();p.addView(t("PAYABLE",10,MUTED,true));p.addView(t("PKR —",25,GOLD,true));p.addView(t("Read-only: source Excel files are never changed.",11,MUTED,false));}
 void settings(){LinearLayout c=card();c.addView(t("Private Data Source",18,Color.WHITE,true));c.addView(t("Paste the permanent HTTPS URL created by the Malik Traders laptop sync tool. It is saved on this phone.",12,MUTED,false));EditText e=new EditText(this);e.setText(source);e.setHint("https://.../malik-traders-data.json");e.setTextColor(TEXT);e.setHintTextColor(MUTED);e.setSingleLine();c.addView(e);TextView save=button("SAVE & TEST CONNECTION");save.setOnClickListener(v->{String u=e.getText().toString().trim();if(!u.startsWith("https://")){Toast.makeText(this,"Please enter a secure HTTPS URL",Toast.LENGTH_LONG).show();return;}source=u;getPreferences(0).edit().putString("source",source).apply();sync(true);});c.addView(save);LinearLayout r=card();r.addView(t("AUTOMATIC REFRESH",12,TEAL,true));r.addView(t("The app checks this saved URL whenever it opens. You do not need to choose a OneDrive folder each time.",13,MUTED,false));}
 void sync(boolean tell){if(source.isEmpty()){if(tell){tab="Settings";render();Toast.makeText(this,"Add your private data URL first",Toast.LENGTH_LONG).show();}return;}new Thread(()->{try{HttpURLConnection h=(HttpURLConnection)new URL(source).openConnection();h.setConnectTimeout(12000);h.setReadTimeout(12000);h.setRequestProperty("Accept","application/json");int code=h.getResponseCode();if(code<200||code>=300)throw new IOException("HTTP "+code);InputStream in=h.getInputStream();ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] buf=new byte[4096];int n;while((n=in.read(buf))>0&&out.size()<2000000)out.write(buf,0,n);String data=new String(out.toByteArray(),StandardCharsets.UTF_8);if(data.trim().isEmpty())throw new IOException("Empty data");last=new java.text.SimpleDateFormat("dd-MM-yyyy, hh:mm a",java.util.Locale.getDefault()).format(new java.util.Date());getPreferences(0).edit().putString("last",last).putString("cache",data).apply();runOnUiThread(()->{render();if(tell)Toast.makeText(this,"Latest data received",Toast.LENGTH_SHORT).show();});}catch(Exception e){runOnUiThread(()->Toast.makeText(this,"Sync failed: "+e.getMessage(),Toast.LENGTH_LONG).show());}}).start();}
}